local G = require('G')

-- Increase the speed of writing Markdown.
G.cmd('autocmd Filetype markdown inoremap <buffer> ,f <Esc>/<++><CR>:nohlsearch<CR>"_c4l')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,w <Esc>/ <++><CR>:nohlsearch<CR>"_c5l<CR>')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,n ---<Enter><Enter>')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,b **** <++><Esc>F*hi')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,s ~~~~ <++><Esc>F~hi')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,i ** <++><Esc>F*i')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,d `` <++><Esc>F`i')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,c ```<Enter><++><Enter>```<Enter><Enter><++><Esc>4kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,m - [ ] ')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,p ![](<++>) <++><Esc>F[a')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,a [](<++>) <++><Esc>F[a')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,1 #<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,2 ##<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,3 ###<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,4 ####<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,5 #####<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,6 ######<Space><Enter><++><Esc>kA')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,l --------<Enter>')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,` ·')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,. <Space>=><Space>')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,> <Space>→<Space>')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,= ===<Space>Output<Space>===')
G.cmd('autocmd Filetype markdown inoremap <buffer> ,v -<Space>`<++>`<Space><++>')
